### ISSUE TITLE
Add support for panics on Windows

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/miri#1059]
Several tests are currently [disabled on Windows](https://github.com/rust-lang/miri/pull/693/commits/80f9484c8680e54a31916d6410a5eea2ddb1e237), due to Miri's lack of support for a number of Windows API functions:

* `GetProcAddress`
* `GetModuleHandleW`
* `AcquireSRWLockShared`

Implementing `GetProcAddress` and `GetModuleHandleW` will require us to extend our current handling of `dlsym` to support Windows. This is currently blocked on https://github.com/rust-lang/miri/pull/1225 ~~https://github.com/rust-lang/rust/pull/66470~~ ~~https://github.com/rust-lang/rust/pull/69326~~, since we need the ability to read wide strings.

**Comment by RalfJung** [comment]
The alternative (which avoids having to implement read-write locks for Windows) is to patch libstd so that `RwLock`, like `Mutex`, falls back to `EnterCriticalSection` when `SRWLock` is not available.

That would also have the added benefit of making panicking work again on Windows XP.

**Comment by CAD97** [comment]
At the very least, it'd be great to have a better, more appropriate error message than "`thread panicked while processing panic. aborting.`". I thought I had a very different problem when I saw that message under miri, when actually everything was working properly, it's just that on Windows miri does not implement panics yet.

I was trying to use miri to implement leak check tests in the face of panics, but because of this I had to fall back to the (probably better, because it works for `cargo test`) approach of tracking `new`/`drop` calls manually.

**Comment by RalfJung** [comment]
If you have any suggestions for how we could get a better error, I'm all ears. The error is emitted by libstd, not by Miri.

Once https://github.com/rust-lang/rust/pull/69729 lands, you should be able to use `--target x86_64-unknown-linux-gnu` on Windows, and then panics should work fine.

**Comment by RalfJung** [comment]
@CAD97 but in your repo, doesn't it run Miri on `ubuntu-latest`? How is this Windows-only issue a problem?

**Comment by CAD97** [comment]
Yeah, CI is running on Ubuntu, but I also am running tests locally, which is a lot lower latency 😝

I'm not exactly certain how best to get a better error message for Windows targets. Didn't miri used to say something along the lines of "panicking not supported"? I'd expect that message still on the Windows target, rather than for the panic to start but than starting the panic but then failing to handle it.

**Comment by RalfJung** [comment]
Ah, good idea... see https://github.com/rust-lang/miri/pull/1241. Testing would be welcome, as I don't have a Windows machine to try this on. :)

**Comment by RalfJung** [comment]
With https://github.com/rust-lang/miri/pull/1249, another alternative for Windows users is to pass `--target x86_64-unknown-linux-gnu` -- cross-interpretation like that should work fine now, and unwinding is supported for Linux targets.

**Comment by RalfJung** [comment]
Solving this by implemented the "shared RW lock" Windows methods would likely also solve https://github.com/rust-lang/miri/issues/1302.

**Comment by RalfJung** [comment]
@CAD97 
> I was trying to use miri to implement leak check tests in the face of panics

Note that Miri currently does not check for leaks on Windows, see https://github.com/rust-lang/miri/issues/1302.
