### ISSUE TITLE
References aliasing is not detected in some cases

### ISSUE THREAD

**Issue by Pzixel** [rust-lang/miri#1119]
Consider following code:

```rust
struct Ref<'a>(&'a mut u8);

impl<'a> Drop for Ref<'a> {
    fn drop(&mut self) {
        println!("dropping {} {:p}", self.0, &self);
    }
}

fn main() {
    let mut a = 0;
    let ref1 = Ref(&mut a);
    *ref1.0 += 1;
    let ptr = ref1.0 as *mut _;
    let ref2 = Ref(unsafe { &mut *ptr });
    *ref2.0 += 1;
}
```

It leads to the double free although MIRI doesn't see anything wrong with it:

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.78s

dropping 2 0x20740
dropping 2 0x20858
```

Interestingly if we run it via rustc

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.46s
     Running `target/debug/playground`

dropping 2 0x7fffe36b8328
dropping 2 0x7fffe36b8328
```

As you can see compiled version shows that addresses are equal but in MIRI they are different.

**Comment by oli-obk** [comment]
> As you can see compiled version shows that addresses are equal but in MIRI they are different.

They are only equal because rustc reuses the storage of `ref_` for `ref2`. 

I don't believe there is anything wrong with this program (also there's no double free). Let me explain:

`a` the variable that we have mutable access to. We must guarantee that there are never two mutable references to the same variable. Well, two *active* mutable references, which is what makes this entire example possible. With "active" I mean the fact that

```rust
let mut x = 42;
let y = &mut x;
let z = &mut *y;
*z += 1;
*y += 1;
x += 1;
assert_eq!(x, 45);
```

is totally legal, but you couldn't swap the order of any of the `+= 1` instructions without getting a borrow error.

Ok back to your example. The variable `a` is what we look at

```rust
let mut a = 0;
```

Here you create a mutable reference, let's call it `mut_ref_1`

```rust
let ref_ = Ref(&mut a);
```
Here you mutate `a` through `mut_ref_1`

```rust
*ref_.0 += 1;
```

Here you create a mutable pointer to `a` from `mut_ref_1`, let's call it `mut_ref_2`

```rust
let ptr_ = ref_.0 as *mut _;
```

Here you reborrow `mut_ref_2` and create a mutable reference, let's call it `mut_ref_3`

```rust
let ref2 = Ref(unsafe {&mut *ptr_});
```

Here you mutate `a` through `mut_ref_3`

```rust
*ref2.0 += 1;
```

Now your code is done and destructors run.

1. the destructor of `ref2` runs, after which `mut_ref_3` is not used anymore, because it does not exist anymore.
2. the destructor of `ptr_` runs, it's a nop, but `mut_ref_2` is now not existing anymore
3. the destructor of `ref_` runs, after which `mut_ref_1` is not used anymore

So all this works nicely, because what you essentially did was write an unsafe version of

```rust
let mut a = 0;
let ref_ = Ref(&mut a);
*ref_.0 += 1;
let ref2 = Ref(&mut *ref_.0);
*ref2.0 += 1;
```

Does this make sense?

**Comment by Pzixel** [comment]
Right, thanks for explanation. Sorry for a wrong alert :)

**Comment by RalfJung** [comment]
> As you can see compiled version shows that addresses are equal but in MIRI they are different.

Address may be reused but that is not guaranteed to happen. And @oli-obk explained why there is nothing wrong with this program. So, closing as not-a-bug.
