### ISSUE TITLE
miri doesn't error on `transmute` between non `repr(C)` types

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/miri#1376]
Nomicon [says] 
> Transmuting between non-repr(C) types is UB

However, miri doesn't produce errors when trying to transmute `non-repr(C)` types.

[says]: https://doc.rust-lang.org/nomicon/transmutes.html?highlight=transmute#transmutes

Example code:

```rust
// Note: non-repr(C)
struct In {
    a: usize,
    b: usize,
}

fn main() {
    unsafe {
        assert_eq!(
            core::mem::transmute::<In, (usize, i64)>(In { a: 1, b: 2}),
            (1, 2),
        )   
    }
}
```

([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=256561c008a0c277836874561efc2b5c))

**Comment by RalfJung** [comment]
This Miri behavior is by design -- the Nomicon is slightly imprecise in its language here. Transmuting between arbitrary type is okay *if you know exactly that the fields are all at the right offsets*. For non-`repr(C)`, the field offsets are not guaranteed and can change any time, and even e.g. `Vec<usize>` and `Vex<isize>` are not guaranteed to have the same field order.

What Miri tells you when you run your example program is that for exactly these types, with exactly the compiler version you used, the code is okay. That is accurate. But changing the compiler or doing seemingly harmless changes to the involved types can break the code, because field order and offsets are not guaranteed.

See [the UCG chapter on layout](https://rust-lang.github.io/unsafe-code-guidelines/layout.html) for more details.

**Comment by RalfJung** [comment]
This is also documented in the Miri README:

> If the program relies on unspecified details of how data is laid out, it will still run fine in Miri -- but might break (including causing UB) on different compiler versions or different platforms.
