### ISSUE TITLE
Fails to detect user after drop (after transmute)

### ISSUE THREAD

**Issue by gmorenz** [rust-lang/miri#1650]
I was surprised when miri failed to catch this, I'm not sure if it might just be considered out of scope for now?

```
use std::mem::transmute;

pub struct Test {
    b: bool,
}

impl Drop for Test {
    fn drop(&mut self) {
        self.b = false;
        println!("Dropping");
    }
}

fn main() {
    let test = Test{  b: true };
    let r = unsafe{ transmute::<&'_ bool, &'_ bool>(&test.b) };
    drop(test);
    println!("{:?}", *r);
}
```

**Comment by RalfJung** [comment]
There's no use-after-free here since there is no free.

There *is* a use-after-drop, but I think the game is still open whether that is UB in itself or not. (Of course it is UB for `Box`, but that will already be detected.)

We had a related issue somewhere that I currently cannot find... about marking memory as uninitialized on move.

**Comment by RalfJung** [comment]
Ah, here is the related issue: https://github.com/rust-lang/unsafe-code-guidelines/issues/188

So, given also that https://doc.rust-lang.org/reference/behavior-considered-undefined.html does not list "use-after-drop" or "use-after-move" as a form of UB in Rust, I think currently there is no bug in Miri here, so I am inclined to close this.

**Comment by gmorenz** [comment]
rust-lang/unsafe-code-guidelines#188 does seem exactly on point... so your inclination seems right to me.
