### ISSUE TITLE
Cheat Miri

### ISSUE THREAD

**Issue by nightkidxmd** [rust-lang/miri#1742]
Build borrow record like below,
Then I can access user.y via ptr successfully.
```rust
#![allow(unused)]
fn main() {
    use std::slice;
    struct Test {
        x: [i32; 3],
        y: i32,
    }
    let user = Test { x: [1, 2, 3], y: 4 };
    let ptr = &(user.x) as *const i32;
    let ptr2 = &(user.y) as *const i32; // build borrow record
    for i in 0..4 {
       unsafe { println!("ptr offset {} : {:?} addr{:?}", i, ptr.offset(i), *ptr.offset(i)) };
    }
    let slice = unsafe { slice::from_raw_parts(ptr, 4) };
    println!("slice[3] : {:?}", slice[3]);
}
```

**Comment by RalfJung** [comment]
Thanks for the report!

This is expected behavior: you created `ptr2`, and since it is a raw pointer, Miri / Stacked Borrows make no attempt at distinguishing that from `ptr`. So now `ptr` also has the "permissions" that were granted to `ptr2`. You can use `-Zmiri-track-raw-pointers` to change this behavior and use more precise tracking, at the cost of not supporting ptr-int-casts any more.

See https://github.com/rust-lang/unsafe-code-guidelines/issues/248 for the underlying Stacked Borrows issue.
