### ISSUE TITLE
ignoring memory leak in specific test

### ISSUE THREAD

**Issue by petrosagg** [rust-lang/miri#1754]
Hi! I have a specific test in my crate that calls `std::mem::leak` on purpose to verify that the crate maintains its invariants even under those circumstances. Is there a non-global way of disabling leak check for the particular test?

**Comment by RalfJung** [comment]
No, that is currently not possible. The leak check happens once, all the way at the end of execution, and just checks that there are no allocations left -- so without a lot of extra infrastructure, we cannot tell which code performed the allocation.

In the standard library, what we usually did is to keep a raw pointer to the leaking allocation somewhere, so that we can properly deallocate it at the end of the test. An alternative would be to do two runs of the test suite, where only the second includes the leaky test, and do the second run with `-Zmiri-ignore-leaks`.

**Comment by petrosagg** [comment]
Ah, good idea with the raw pointer! I'll do that instead, thank you

**Comment by RalfJung** [comment]
Also, Cc https://github.com/rust-lang/miri/issues/1481

**Comment by SpecificProtagonist** [comment]
Given that allocations now capture backtraces (rust-lang/rust#109061) which can be used to identify the test, can this issue be reopened?

**Comment by RalfJung** [comment]
Given how old the issue is, IMO it's better to file a new issue with up-to-date information.

Note that "test" is not a concept Miri understands. What I could imagine here is something along the lines of "ignore leaks of allocations created in certain functions", and the tricky bit will be identifying the functions.
