### ISSUE TITLE
Is our Windows Argument handling correct?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1881]
Windows programs receive the CLI arguments as a single long string, but Miri gets the already separated arguments from `std::env` -- so to emulate Windows programs, we have to construct the one-string version from that:

https://github.com/rust-lang/miri/blob/d4a76a9ef113f733ae992fdff080ce1bfa7c408b/src/eval.rs#L214-L223

Our tests ensure that this is at least [not entirely broken](https://github.com/rust-lang/miri/blob/master/test-cargo-miri/run-test.py#L97). However, I am not sure if this will truly handle all cases correctly.

@ChrisDenton I saw you recently fixed things here on the standard library side, would be great if you could also take a look at what Miri is doing to ensure that it is correct. :)

**Comment by ChrisDenton** [comment]
Sure, I'll take a look. My initial impression is that it's technically wrong but probably not in ways that will be noticed.

The main issue is that `argv[0]` follows different rules to the other arguments. It cannot contain a literal `"` character so attempting to escape it would not do what you'd expect. On Windows this is unlikely to be an issue because `argv[0]` is, by convention, the executable path and Windows file names cannot contain `"`. And even on Linux it would be unusual to use `"` in a file name.

I was concerned about the use of `shell_escape` because the docs for it talk about escaping characters in "cmd.exe". But it looks as though the actual implementation does what you'd want. However, not knowing anything about that crate, I'd be worried an update could change that.

I'll look at it more in-depth when I have a bit more time.

**Comment by RalfJung** [comment]
> The main issue is that argv[0] follows different rules to the other arguments. It cannot contain a literal " character so attempting to escape it would not do what you'd expect. On Windows this is unlikely to be an issue because argv[0] is, by convention, the executable path and Windows file names cannot contain ". And even on Linux it would be unusual to use " in a file name.

Okay, so sounds like the correct thing would be to just panic when there is a `"` in the filename. (If that is ever a problem for someone, we can figure out what to do then.)

> I was concerned about the use of shell_escape because the docs for it talk about escaping characters in "cmd.exe". But it looks as though the actual implementation does what you'd want. However, not knowing anything about that crate, I'd be worried an update could change that.

Yeah, it might be better to just have something in-tree. I went for shell_escape because I did not have the slightest idea what I was doing, and this made the tests pass.^^

> I'll look at it more in-depth when I have a bit more time.

Thanks a lot. :) This is by no means urgent, we've been using the same code for >1 year now and there were no bug reports yet.

**Comment by ChrisDenton** [comment]
Sorry it took me awhile to come back to this.

So to recap, it'd be good to have a function in miri that correctly builds the command line string from an array of arguments. I'm not familiar with miri's code so where would be the best place to put such a function?

**Comment by RalfJung** [comment]
> I'm not familiar with miri's code so where would be the best place to put such a function?

A private fn inside `eval.rs` would be best I think.
