### ISSUE TITLE
MIRI algorithm and Benckmarking to check performance

### ISSUE THREAD

**Issue by MJUCOM** [rust-lang/miri#1965]
HI all!

I'm interested in RUST's security technology, so I'm studying MIRI. I have a questions about  MIRI and I would like to get professional advice.

1. I want to understand the inner workings of MIRI and the algorithm of MIRI by knowing the internal operation of detecting bugs.  Are there any reference files or contents where I can study MIRI`s algorithm to detect the bugs?

1. I also want to apply the MIRI to the RUST program to verify the MIR code. To generate the MIR code, I tried many attempts by building the program through cargo package and try the commend such as ‘cargo miri run -- --emit=mir’ , but there is a difficulty in generating the MIR code. Is there any way to apply MIRI to generate MIR code during the build process?

1. Lastly, I want to check performance of MIRI, so is there a way to apply benchmarking to the RUST program that applies MIRI??

Thanks for reading!

**Comment by oli-obk** [comment]
> 1. Are there any reference files or contents where I can study MIRI`s algorithm to detect the bugs?

The original miri was written as part of a thesis as outlined in https://github.com/rust-lang/miri#history where you'll also find the relevant thesis and presentation.



> 2\. I also want to apply the MIRI to the RUST program to verify the MIR code. To generate the MIR code, I tried many attempts by building the program through cargo package and try the commend such as ‘cargo miri run -- --emit=mir’ , but there is a difficulty in generating the MIR code. Is there any way to apply MIRI to generate MIR code during the build process?

You don't need to (and can't anyway) build MIR and run miri on it. You run miri directly on your Rust program. Instructions to do so can be found at https://github.com/rust-lang/miri#using-miri



> 3\. Lastly, I want to check performance of MIRI, so is there a way to apply benchmarking to the RUST program that applies MIRI??

Well... miri is slow, unless you plan to work on miri itself to improve its performance, there is little use in benchmarking it. Even then, you'll need to dig in really deep into miri's scheme for executing a Rust program in order to run tools like valgrind on it. This is not as easy as running miri and we likely can't be of much help to you when/if you do this.

**Comment by MJUCOM** [comment]
Thank you for your comment !!
