### ISSUE TITLE
Miri hangs on running with miri-compare-exchange-weak-failure-rate=1

### ISSUE THREAD

**Issue by alygin** [rust-lang/miri#2160]
To reproduce:

```bash
cargo init miri-test
cd miri-test
echo "#[test] fn test() {}" >> src/main.rs
MIRIFLAGS="-Zmiri-compare-exchange-weak-failure-rate=1" cargo miri test
```

The process hangs on "Running unittests src/main.rs...", without actually running the test.

It works fine with any other valid value of `miri-compare-exchange-weak-failure-rate`.
The problem is not reproducible with the `nightly-2022-05-22` toolchain.

**Comment by RalfJung** [comment]
Thanks for the report!

Setting the failure rate to 1 means it always fails, as it says in the docs. It is expected then that programs hang, since their weak compare exchanges never succeed, so they never can make progress.

We recently fixed a bug here with https://github.com/rust-lang/miri/pull/2105; that's why you did not see this behavior before.

**Comment by alygin** [comment]
Oh, that makes sence, thanks, @RalfJung!
