### ISSUE TITLE
autocfg assumes there is no std

### ISSUE THREAD

**Issue by youknowone** [rust-lang/miri#2431]
This code was running ok with previous version of miri, but not today version.
```rust
// cargo add indexmap
fn main() {
    let _ = indexmap::IndexMap::<u32, String>::new();
}
```

error:
```
error[E0107]: this struct takes 3 generic arguments but 2 generic arguments were supplied
  --> src/main.rs:2:23
   |
2  |     let _ = indexmap::IndexMap::<u32, String>::new();
   |                       ^^^^^^^^   ---  ------ supplied 2 generic arguments
   |                       |
   |                       expected 3 generic arguments
   |
note: struct defined here, with 3 generic parameters: `K`, `V`, `S`
  --> /home/youknowone/.cargo/registry/src/github.com-1ecc6299db9ec823/indexmap-1.9.1/src/map.rs:76:12
   |
76 | pub struct IndexMap<K, V, S> {
   |            ^^^^^^^^ -  -  -
help: add missing generic argument
   |
2  |     let _ = indexmap::IndexMap::<u32, String, S>::new();
   |                                             +++

error: aborting due to previous error

For more information about this error, try `rustc --explain E0107`.
error: test failed, to rerun pass '--bin miritest'
```

In the indexmap code, I found it is hitting `#[cfg(not(has_std))]`

```rust
#[cfg(has_std)]
pub struct IndexMap<K, V, S = RandomState> {
    pub(crate) core: IndexMapCore<K, V>,
    hash_builder: S,
}
#[cfg(not(has_std))]
pub struct IndexMap<K, V, S> {
    pub(crate) core: IndexMapCore<K, V>,
    hash_builder: S,
}
```

**Comment by RalfJung** [comment]
So looks like [this code here](https://github.com/bluss/indexmap/blob/a638b9910b08f45d2e5f90536855789a90fcbbe6/build.rs) now decided that we don't have std. What exactly does `autocfg::new().emit_sysroot_crate("std")` do?

My hunch would be that it has to do with this recent change:

https://github.com/rust-lang/miri/blob/master/cargo-miri/bin.rs#L757-L766

**Comment by RalfJung** [comment]
Oh lol, it [runs rustc on some code and checks the results](https://github.com/cuviper/autocfg/blob/01f9075c2b8e8df4c7fd18f5e39af716a92f7722/src/lib.rs#L205). Yeah that has no realistic chance of working. It worked mostly by chance before...

We'd have to somehow ensure that MIRI_BE_RUSTC=host is set when build scripts are run. And even then the test is kinda meaningless since it would not be run for the target we are actually building for. Autocfg also passes on the TARGET it seems, but for the target we simply don't have a sysroot it could use. So this was probably already broken before in cross-compilation mode.

**Comment by RalfJung** [comment]
Ah here we go, I have an error message:
```
  error: miri can only run programs that have a main function
```
So looks like we need to make Miri parse the `--emit` flag (or access whatever parsed form of it that rustc has) and skip interpretation if this is not actually supposed to produce a binary.

**Comment by youknowone** [comment]
Thank you!
