### ISSUE TITLE
Make Atomic RMWs always fail on read-only memory

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2463]
[This example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4cf12a768c92b0b4ec3fcdb03644fb41) should probably fail even with Stacked Borrows disabled. (It also segfaults at runtime.)

**Comment by RalfJung** [comment]
That said, doing this the "obvious" way will also trigger all the other write hooks, and I am not sure that would be correct. On the one hand it raises https://github.com/rust-lang/unsafe-code-guidelines/issues/355, on the other hand I think the atomic memory model *does* make a fundamental difference between successful and failed RMWs (failed RMWs do not enter the `mo` order).

**Comment by RalfJung** [comment]
In particular this becomes relevant for the Stacked Borrows successor, where we want to see https://github.com/rust-lang/unsafe-code-guidelines/issues/303 fixed -- that would also "fix" Miri to accept the original example, which we don't want.

**Comment by taiki-e** [comment]
I think (at least DW) atomic load also needs to fail on read-only memory.

The instructions generated by `Atomic*128::load` for aarch64 without lse2, `Atomic*128::load` for x86_64, and `Atomic*64::load` for x86 without sse&x87 all always write to memory: [godbolt](https://godbolt.org/z/nvooxffzr)

Also, on pre-v6 ARM linux, [atomic load calls `__sync_val_compare_and_swap_N`](https://godbolt.org/z/fMenYxzre), which [calls `__kuser_cmpxchg`](https://github.com/rust-lang/compiler-builtins/blob/8672395c985dc0c49b5ec738fa258b121f74df40/src/arm_linux.rs). I have not read the implementation of [`__kuser_cmpxchg`](https://www.kernel.org/doc/Documentation/arm/kernel_user_helpers.txt), but this may have a similar problem because the value is written if the comparison is successful.

**Comment by RalfJung** [comment]
> I think (at least DW) atomic load also needs to fail on read-only memory.

What's DW?

> The instructions generated by Atomic*128::load for aarch64 without lse2, Atomic*128::load for x86_64, and Atomic*64::load for x86 without sse&x87 all always write to memory

Uh wtf what?^^

**Comment by RalfJung** [comment]
I can't read assembly very well but it seems this is using a compare_exchange to implement a load? Interesting.

But that's a hardware architecture thing, so I *think* it is enough to just reject this on read-only memory, but it doesn't mean we need to consider this a write for any other part of the memory model. Stacked Borrows treating this as read-only should still be sound, right?

For example, if another thread does non-atomic loads concurrently with the first thread doing a failing compare_exchange, or one of these u128 atomic loads -- can anything strange happen, are there ever "wrong values" in memory for some intermediate moment in time, or is this really just a strange quirk of the x86 page tables we have to work around?

**Comment by taiki-e** [comment]
> What's DW?

double-width

> But that's a hardware architecture thing, so I think it is enough to just reject this on read-only memory, but it doesn't mean we need to consider this a write for any other part of the memory model. Stacked Borrows treating this as read-only should still be sound, right?

Yeah, IMO, the problem is using atomic operations on read-only memory, and since the value is not changed, things like concurrent non-atomic loads from other threads should be fine. (If not, things like emulating 8-bit CAS using 32-bit CAS used on mips, powerpc, riscv, etc. would also be unsound. Since they also write to the memory around the target memory)

> is this really just a strange quirk of the x86 page tables we have to work around?

I believe this is a read-only memory-specific problem, but I don't believe this should be considered an x86-specific problem -- I tested a 128-bit atomic load into read-only memory on aarch64 linux and I got SIGSEGV. 

> On the hardware level this then should mean it's not really observable by other threads?

Probably depends on the architecture; architectures that implement CAS using [LL/SC](https://en.wikipedia.org/wiki/Load-link/store-conditional) may cause weak CAS in other threads to fail (I can confirm this on aarch64).

**Comment by RalfJung** [comment]
> emulating 8-bit CAS using 32-bit CAS 

The things you learn...

> may cause weak CAS in other threads to fail

Legally speaking it could have failed anyway even if no other thread did anything, so that is fine.
(And also now I finally understand why weak CAS even exists, it's for LL/SC architectures -- thanks for enlightening me :D )

**Comment by taiki-e** [comment]
> Legally speaking it could have failed anyway even if no other thread did anything, so that is fine.

Yeah, that is definitely okay. 

> > emulating 8-bit CAS using 32-bit CAS

Well, I should probably have said, "emulate 8-bit/16-bit atomic RMWs using 32-bit atomic operations" to be exact. (Some architectures lack instructions for atomic RMWs that are smaller than the word size (32-bit). On such architectures, 8-bit and 16-bit atomic RMWs are emulated using 32-bit CAS loop or LL/SC loop. [Rounded down the address of the pointer to a multiple of 4, load the 32-bit value, mask the value as only to operate a part of it, and store it by 32-bit CAS or SC](https://github.com/llvm/llvm-project/blob/llvmorg-15.0.0-rc1/llvm/lib/CodeGen/AtomicExpandPass.cpp#L807-L814)...)

If the memory model considers a write that is guaranteed to be no-op as "write", it should not be possible to implement atomic in such a way, because concurrent non-atomic reads to memory around an atomic value will be considered data race.

**Comment by RalfJung** [comment]
> If the memory model considers a write that is guaranteed to be no-op as "write"

The Rust memory model does, so this would not be a legal implementation in Rust.

But if this is done at the end of the pipeline when generating assembly, it is fine -- hardware memory models AFAIK don't have a problem with this.

**Comment by taiki-e** [comment]
> > If the memory model considers a write that is guaranteed to be no-op as "write"
> 
> The Rust memory model does, so this would not be a legal implementation in Rust.
> 
> But if this is done at the end of the pipeline when generating assembly, it is fine -- hardware memory models AFAIK don't have a problem with this.

You are right. I should have said something like "If hardware memory models consider a write to non-read-only memory that is guaranteed to be no-op as write..."

**Comment by RalfJung** [comment]
Yes. I hope the targets that emulate small CAS using larger CASes don't have problems with concurrent non-mutating writes. :D
