### ISSUE TITLE
Surprising behaviour of `from_raw_parts`

### ISSUE THREAD

**Issue by Voultapher** [rust-lang/miri#2689]
I'm trying to write code that passes a pointer correctly via FFI from Rust -> C -> Rust, while respecting strict provenance. I wrote this code which I would assume preserves the provenance information or at-least triggers my assert that it can't store the provenance information in a `u64`.

```rust
#[derive(PartialEq, Eq, Debug, Clone)]
#[repr(C)]
struct CompCount {
    val: i32,
    comp_count: Cell<u32>,
}

fn main() {
    type CompCountRawPartsMut = (*mut (), <CompCount as ptr::Pointee>::Metadata);
    type CompCountRawParts = (*mut (), <CompCount as ptr::Pointee>::Metadata);

    let self_ptr: CompCountRawPartsMut =
        Box::into_raw(Box::new(CompCount::new(3))).to_raw_parts();

    assert!(mem::size_of::<CompCountRawPartsMut>() == mem::size_of::<u64>());
    // Over-aligning is ok.
    assert!(mem::align_of::<CompCountRawPartsMut>() <= mem::align_of::<u64>());

    let val: u64 = unsafe { mem::transmute::<CompCountRawPartsMut, u64>(self_ptr) };

    let (addr, metadata) = unsafe { mem::transmute::<u64, CompCountRawParts>(val) };
    let self_ptr_read: *const CompCount = ptr::from_raw_parts(addr, metadata);

    let x: &CompCount = unsafe { &*self_ptr_read };
    dbg!(x);

    // drop code omitted for brevity.
}
```

When I run this, I get: `is a dangling pointer (it has no provenance)`

**Comment by Voultapher** [comment]
I guess `val` is a number and has now lost any meaning as pointer, but I was still surprised by the effect. I had assumed that `to_raw_parts` gives me all the necessary information including provenance in the metadata. But probably that's the wrong mental model, can you even serialize provenance?

**Comment by saethlin** [comment]
You aren't respecting strict provenance. The whole idea of strict provenance is to not store pointers as integers, because round-tripping pointers through integers has complicated semantics which we aren't completely sure of yet.

What we are basically totally sure of is that you cannot round-trip via transmutes, which is what you are trying to do here. The reason for this is that there are many ways to transmute in Rust that do not involve calling the function, so a model that permits this adds a lot of complexity to all loads of integer type.

If you need to round-trip, use casts. The documentation for all the core strict provenance APIs may be helpful, consult `ptr::addr`, `ptr::invalid`, `ptr::expose_addr`, and `ptr::from_exposed_addr`. The former are transmutes and the latter are currently implemented with `as` casts. It sounds to me like you need expose semantics as a result of a C API smuggling a pointer type through an integer type API.

**Comment by RalfJung** [comment]
> can you even serialize provenance?

No, you cannot -- provenance is purely a 'ghost' component of the Abstract Machine that flows with each pointer, and disappears when the pointer is turned into an integer. Provenance cannot be attached to anything but pointers (and entirely untyped data, aka `MaybeUninit<T>`).

**Comment by Voultapher** [comment]
Thanks for the clarification, I think I was thinking too much in terms of CHERI where provenance is some concrete information in the form of bits. As a hint if you aren't aware of this already, I found the documentation surrounding this topic to be rather confusing, even as someone who thought of himself as familiar with the concept.

**Comment by RalfJung** [comment]
Yeah, sadly we don't have good docs on this yet because we are still in the process of slowly nudging Rust into accepting that provenance is a thing. ;)  Things that are officially documented are basically stable promises, and the lang team is not yet ready to make stable promises on these details of the provenance model.

So, everything we say here should be taken with a heavy load of salt, and is subject to future changes. I *think* Miri implements the model of provenance we will eventually want to have, but I cannot promise that.

**Comment by saethlin** [comment]
Did you read the documentation for `ptr::addr`? It is intended to explain that you cannot do what you were trying to do. If it doesn't, can you advise on any changes?
