### ISSUE TITLE
ICE when dealloc causes Stacked Borrows error

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2693]
I realized we don't have a test hitting [this](https://github.com/rust-lang/miri/blob/435faf0052ba0bd628bab5c531c74379a7462758/src/stacked_borrows/diagnostics.rs#L456), and indeed trying to do so currently ICEs:
```rust
use std::alloc::{alloc, dealloc, Layout};

fn main() { unsafe {
    let x = alloc(Layout::from_size_align_unchecked(1, 1));
    let ptr1 = (&mut *x) as *mut u8;
    let ptr2 = (&mut *ptr1) as *mut u8;
    // Invalidate ptr2 by writing to ptr1.
    ptr1.write(0);
    // Deallocate through ptr2.
    dealloc(ptr2, Layout::from_size_align_unchecked(1, 1));
} }
```
produces
```
thread '<unnamed>' panicked at 'internal error: entered unreachable code: access_error should only be called during an access', src/stacked_borrows/diagnostics.rs:398:13
```
The trouble is here:
https://github.com/rust-lang/miri/blob/2f92cf2d26c6b7e16715b900dc3d7d021f8afb40/src/stacked_borrows/mod.rs#L477-L480
We try to use `map_err` to make this a deallocation error, but when that happens `access` has already called `dcx.access_error`, causing the ICE. (The ICE is a regression introduced by https://github.com/rust-lang/miri/pull/2684.)

@saethlin any idea how to best fix this?

**Comment by RalfJung** [comment]
I feel like `access_error` should just use the information present in `self.operation` to make a nice error.

**Comment by saethlin** [comment]
`grant_error`, `access_error`, and `dealloc_error` only work with one kind of `Operation` each. `protector_error` however recognized 3 kinds of `Operation`. So if you can find a way to merge all 3 of `grant_error`, `access_error`, and `dealloc_error` together into a function with a decent name which branches on `Operation` to figure out what error text to emit, and when presented this program mentions a deallocation that sounds good to me. I'm not sure if that is workable though.

Special-casing `access_error` for this code pattern doesn't seem right to me, because there is no memory access. But perhaps there another generalization we are missing, because the way you (or SB) use "access" is not necessarily in line with "a read or write to memory". SB does an as-if access inside `grant`. Maybe I'm just grumpy about the fact that there is no distinction between "a read or write to memory" and "a virtual access that establishes aliasing guarantees" in the nomenclature. So perhaps there should be a branch inside `access_error`, and we should adjust the names so that it makes more sense.

**Comment by RalfJung** [comment]
Yeah, some of our 'access' mean 'do all the things we would do for a memory access, as a way to enforce some aliasing property', and some mean 'an actual load/store'. But the codebase was already confused about that before, https://github.com/rust-lang/miri/pull/2694 (which makes `access_error` also work fine for retags and dealloc) doesn't really make it any worse.

**Comment by saethlin** [comment]
So yes I think I think #2694 is _good enough_ with the somewhat-confused status of our naming.
