### ISSUE TITLE
`./miri build` failed in Ubuntu 22.04

### ISSUE THREAD

**Issue by yunji-yunji** [rust-lang/miri#2703]
I was following the instructions in `CONTRIBUTING.md` to add some functions to Miri. 
I tried to fix line 14 and 104 in `miri/cargo-miri/src/phases.rc` file to fix this issue but it didn't work. (My branch is up to date with 'origin/master'.)

Is there something that I missed?

### Environment
- OS: Ubuntu 22.04 LTS
- Processor: 11th Gen Intel® Core™ i7-1165G7 @ 2.80GHz × 8

### Command that I used
`./miri build`

### Error
![image](https://user-images.githubusercontent.com/39113997/204167820-08e2dd95-3e94-46c2-9313-dc16731f1904.png)

**Comment by saethlin** [comment]
Currently (and at the time this issue was created) on `master`, line 104 is a comment. I don't see a fork you've made of Miri, so it seems most likely that you have edited the code in some way to produce this error. What changes did you make? In cases like this it is nice to have a fork you can push your changes to, but if they are small, the output of `git diff` could work to share what you have changed.

If you have not changed anything and you just have an old checkout, `git log -n1` would let us know what commit you are looking at so there is more chance of understanding this.

**Comment by yunji-yunji** [comment]
Thank you so much!
I cloned `master` at a different location again and it works now. I think I edited something in the wrong way.
