### ISSUE TITLE
What about realloc(ptr, 0)

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2774]
Turns out that C [recently declared `realloc(ptr, 0)` to be UB](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2464.pdf) since they couldn't agree on how to unify the diverging behavior of different platforms.

So... probably we should adjust Miri to also raise a UB error in that case? `realloc` is not a Rust function, it is ultimately defined by C, so unless we somewhere document this as an extra platform requirement we are kind of forced to follow the C standard here, I think.

Cc @rust-lang/wg-unsafe-code-guidelines since it seems relevant, even though it is just a Miri thing (the Rust primitive `__rust_realloc` already has UB on size 0 in Miri, matching `__rust_alloc`).

**Comment by digama0** [comment]
This is LLVM's call, not C's, no? I think it is reasonable to expect they would follow suit, but it's not a problem for us until LLVM changes their semantics and we could put a word in to affect the decision if necessary.

**Comment by bjorn3** [comment]
I don't think this is LLVM's call. The allocator is allowed to invoke UB in it's realloc implementation if the size is 0 due to this C change. LLVM may additionally optimize based on the knowledge that the size will not be 0, but even if it doesn't you could still get UB from the allocator. In addition even if LLVM and the allocator don't consider it UB, another codegen backend for rustc may still do so.

**Comment by RalfJung** [comment]
Yeah `__rust_realloc` already has UB on size 0, or at least Miri models it that way. (That one is entirely Rust's call, there is no realloc primitive in LLVM. At least the LangRef doesn't mention anything.)
