### ISSUE TITLE
 Why it could be UB that Pin::new_unchecked on an &’a mut T has dropped? 

### ISSUE THREAD

**Issue by gftea** [rust-lang/miri#2810]
Why below example about[ `pin::new_unchecked`](https://doc.rust-lang.org/std/pin/struct.Pin.html#method.new_unchecked) is UB?
If T is `Unpin`, it seems to be OK, 
if T is `!Unpin`, then `mem::swap` would result in wrong behavior.

But why it is UB here? Does compiler neglect lifetime for `p`, and do something/optimization based on its memory will not get invalidated or repurposed from the moment it gets pinned until when [drop](https://doc.rust-lang.org/std/ops/trait.Drop.html#tymethod.drop) is called?

```rust

fn move_pinned_ref<T>(mut a: T, mut b: T) {
    unsafe {
        let p: Pin<&mut T> = Pin::new_unchecked(&mut a);
        // This should mean the pointee `a` can never move again.
    }
    mem::swap(&mut a, &mut b); // Potential UB down the road ⚠️
    // The address of `a` changed to `b`'s stack slot, so `a` got moved even
    // though we have previously pinned it! We have violated the pinning API contract.
}
```

If it should be UB, current MIRI does not detect this.

[example from std](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c9a8e7bb5f017851944c48c457e9dfcb)

**Comment by RalfJung** [comment]
The comment clearly says "Potential UB down the road". So the code itself is wrong, and violates Pin safety guarantees, but is not itself (language) UB. This is not uncommon in unsafe Rust code, e.g. consider
```rust
let mut v: Vec<Box<i32>> = Vec::with_capacity(10);
unsafe { v.set_len(10) }; // no UB here! But potential UB down the road.
// But now the vector is in a bad state, and the next line will be UB.
drop(v);
```

I don't know if this answers your question, since I was confused about what you are asking. But I think it has little to do with Miri; if you need help understanding the pinning API contract, https://users.rust-lang.org/ is a good place to ask.

**Comment by gftea** [comment]
Thanks, I see what you meant
