### ISSUE TITLE
can't call foreign function: malloc/free

### ISSUE THREAD

**Issue by dead-claudia** [rust-lang/miri#2831]
I'm linking with a library that [uses libc for some of its allocations (but offloads the freeing to the user)](https://www.freedesktop.org/software/systemd/man/sd_journal_get_cursor.html) and it'd be nice to be able to test my wrapper within Miri without needing to shim them.

They're easy to shim: you can just store the allocation size with the allocation itself in `malloc` and friends and then read it before you deallocate it in `free` so you can get the layout to `dealloc` with.

You could also track what allocator type allocated what, to ensure stuff that's allocated with `malloc` is deallocated with `free` and stuff that's allocated with `alloc` is deallocated with `dealloc`.

**Comment by oli-obk** [comment]
I'm not sure how you are getting that error, but

```rust
extern "C" {
    fn malloc(x: usize) -> *const ();
    fn free(x: *const ());
}

fn main() {
    unsafe {
        let x = malloc(42);
        free(x);
    }
}
```

works (you can even run it on miri in the playground).

Do you have an example that fails?

**Comment by bjorn3** [comment]
I think OP is calling into a C library using the experimenal libffi support. This C library allocates memory and then requires you to call free yourself.

> They're easy to shim: you can just store the allocation size with the allocation itself in malloc and friends and then read it before you deallocate it in free so you can get the layout to dealloc with.

If the C library calls malloc, miri knows absolutely nothing about this. How did you actually call this C function? The libffi support in miri doesn't allow passing passing and returning pointers. It only supports integers. https://github.com/rust-lang/miri/blob/master/src/shims/ffi_support.rs

**Comment by saethlin** [comment]
It sounds to me like none of the checks you are looking for need Miri. The actual implementation of these would be a bit complicated because the default global allocator _is_ `malloc`/`free`. You'd need to implement both a Rust global allocator yourself and a C allocator.

But you don't need type information to implement these checks, so you can do this in an allocator implementation that is designed to find bugs. I wish Miri could help you here but for the foreseeable future we won't be in a good position to, and these checks can be implemented separately so they probably should be. I previously worked on a Rust global allocator designed to expose bugs. The relevant team didn't want such a thing in the standard library until it had seen use on its own; I wasn't in a good position to do something like that but maybe you are?

**Comment by dead-claudia** [comment]
> I think OP is calling into a C library using the experimenal libffi support. This C library allocates memory and then requires you to call free yourself.

That stuff is obviously shimmed out (and not just because of Miri), and I'm not proposing anything related to that.

I'll just close this issue as effectively an invalid issue in the meantime.
