### ISSUE TITLE
Stacked Borrows changes semantics when called in a function

### ISSUE THREAD

**Issue by CeleritasCelery** [rust-lang/miri#2873]
If we have the following code, Miri flags an error (as we would expect) under the stacked borrows model

```rust
fn main() {
    let x = &mut 5_usize;
    let ptr = x as *mut usize;
    *x = 6;
    let _y = unsafe { &*ptr };
}
```

However if we take the mutation and move it into a function then miri no longer complains

```rust
fn f(x: &mut usize) {
    *x = 6;
}

fn main() {
    let x = &mut 5_usize;
    let ptr = x as *mut usize;
    f(x);
    let _y = unsafe { &*ptr };
}
```

This seems to me like it should have the exact same issue as the first code snippet, but it doesn't. What is going on here? why does doing the operation in a function make it permissible?

### version
rustc 1.71.0-nightly (8bdcc62cb 2023-04-20)

**Comment by RalfJung** [comment]
This is probably because of two-phase borrows: the `x` in the `f(x)` is implicitly an `&mut-twophase *x`. Stacked Borrows treats two-phase borrows like raw pointers since they allow too many things in safe code to impose a stack-like aliasing discipline.

If you run Miri with tree borrows (`-Zmiri-tree-borrows`), that should have better support for two-phase borrows, but it also has other differences. It should actually allow both versions of your code: `ptr` is explicitly created as an alias of `x` and thus Tree Borrows considers both of these pointers to be allowed to alias with each other.
