### ISSUE TITLE
Detect incorrect use of ZST in the allocator?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#3208]
https://github.com/rust-lang/rust/pull/113113 fixed some bugs in ZST handling of the core collections. I wonder if there is a way that Miri could help find those bugs?

Unfortunately the Rust global allocator says that allocating ZST is UB, so when the collections use the global allocator then ZST allocations never reach Miri -- or put differently, there's not actually a bug with `Vec<T, Global>`. So I guess to detect this we'd have to explicitly use `Vec<T, System>`? Then we could make the Miri implementation of malloc actually create a new (zero-sized) allocation on `malloc(0)`, and so failing to pass that to `free` would be a leak. Passing a dangling pointer to `free` is already UB (except if it is NULL) so we should also be able to detect that case.

However, currently I don't think that would help. `System::alloc` ends up [here](https://github.com/rust-lang/rust/blob/3dde25edc46267cd21ab189af84cad100811b204/library/std/src/alloc.rs#L135-L149) so we never end up even calling `malloc(0)`. I guess we'd need our own allocator for this test that wraps `malloc` more directly?

Cc @thomcc @Amanieu maybe you have some further ideas here.

**Comment by Amanieu** [comment]
https://github.com/rust-lang/rust/pull/113113 was only concerned with the `Allocator` interface which, unlike `GlobalAlloc`, does allow allocating ZSTs. The problem was that ZSTs were being freed while not allocated and/or allocated and then leaked.

I don't think that it's Miri's job to catch this since this is library UB (the requirements of the `Allocator` trait are being violated). You would want some form of ZST-tracking allocator to verify this, somewhat like the one used in the tests of that PR.

**Comment by RalfJung** [comment]
Okay, let's close this then.
