### ISSUE TITLE
"./miri test" is very slow on repeated executions

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#3297]
Running `./miri run --dep` multiple times is very slow. The first time I guess it is building parts of Miri or so (`./miri run` doesn't print *any* updates about what it does, making this hard to figure out), but the 2nd time it shouldn't have to do any of that -- and yet, it is slow.

Needless to say, this is quite painful when debugging a pass-dep test.

**Comment by RalfJung** [comment]
It's not just "./miri run". "./miri test" and "./miri build" have the same issue.

This was fine until recently, so something must have changed somewhere to break this... *sigh*

**Comment by RalfJung** [comment]
I think it has to do with ui_test dependency building.

Repeating "./miri test hello" is fine, but repeating a pass-dep test rebuilds a lot of stuff.

Cc @oli-obk -- somehow it seems like ui_test dependency building is now polluting Miri's own build cache?

**Comment by oli-obk** [comment]
Huh. We're still on a version from October. I'll investigate

**Comment by RalfJung** [comment]
Turns out this has been ongoing for a while.
f006d42618a038f7e38d2b59d1b0664727e51382 is still bad.

**Comment by RalfJung** [comment]
Bisecting says this is the bad PR: https://github.com/rust-lang/miri/pull/3252.

That did indeed touch the "deps build" logic, by adding an env var.

**Comment by bjorn3** [comment]
As far as I can tell the `RUSTFLAGS` are passed to a `cargo run` of cargo-miri with the same target dir as miri. As such any shared dependencies will see a different `RUSTFLAGS` between building miri / the regular build of cargo-miri and the `cargo run` of cargo-miri for the purpose of building the test dependencies. I think it would be possible to fix this by directly running the previously built cargo-miri executable rather than rebuilding it with empty `RUSTFLAGS`.

**Comment by RalfJung** [comment]
Oh I see, so the issue isn't that dep builds get mixed with the other builds but that we're re-building `cargo-miri` inside the dep build...
