### ISSUE TITLE
Implement `gettid`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#3730]
Miri supports `getpid` but not `gettid`. It is tempting to implement `gettid` as just returning the internal thread ID, but we have to be careful about this requirement:

> In a single-threaded process, the thread ID is equal to the process ID (PID, as returned by getpid(2)).

**Comment by Mandragorian** [comment]
I could give this a try, but I might not have a lot of spare time until the coming weekend.

I assume a good place to start looking for inspiration is:
 https://github.com/rust-lang/miri/blob/master/src/shims/unix/foreign_items.rs#L83 (?)

**Comment by RalfJung** [comment]
No worries, this is not urgent at all. :)

The main issue is the requirement I quoted above. I wonder if it wouldn't be best to change `getpid` to always return a constant "fake" PID (similar to what getuid already does), like 1000, and then gettid can simply return 1000 + the internal thread ID -- that will ensure that on the main thread, getpid() == gettid(). I am not sure what anyone would do with knowing the true PID inside Miri...

**Comment by Mandragorian** [comment]
That seems like the simplest approach.

Was there a reason why `getpid` was implemented to return the real PID? Would miri need to support programs that spawn different processes (or does it do it already)? Then having a hard-coded PID might be problematic.

Instead of hardcoding a value for `getpid` could another option be to return `getpid() + active_thread_id`?

**Comment by RalfJung** [comment]
> Was there a reason why getpid was implemented to return the real PID? 

I think the answer is "it was easy to do", since `std::process::id()` exists.

Miri does not support process spawning at the moment.

> Instead of hardcoding a value for getpid could another option be to return getpid() + active_thread_id?

That would work, but only when isolation is disabled. With isolation enabled we should then still fall back to some hard-coded value + active_thread_id.

**Comment by Mandragorian** [comment]
Ok then I think for now the simplest approach is to just return a hard-coded value from `getpid` and add to it the internal thread id in `gettid` as you suggested. Otherwise we might overcomplicate things for no reason.

I am not sure I understand how that works when isolation is disabled though. Can't a program try to get its own pid, and then read `/proc/<pid>/` to get some information about itself?

**Comment by Mandragorian** [comment]
Actually I see that `getpid` is not available when isolation is enabled. Do we want to support `gettid` with isolation enabled and disabled?

**Comment by saethlin** [comment]
> Actually I see that `getpid` is not available when isolation is enabled.

The point of isolation is to provide complete determinism, primarily this helps for testing concurrency issues that require specific interleaving of threads or specific weak memory emulation behavior. So the behavior when isolation is enabled just needs to be the same between runs.

> Do we want to support `gettid` with isolation enabled and disabled?

Definitely. There's a pattern for concurrent data structures where threads use their thread ID to select a shard, and it would be good to test that sort of code as fully as possible in Miri.

**Comment by RalfJung** [comment]
Okay, so let's go with -- the PID is some fixed value when isolation is enabled, and is the real PID otherwise. TID is always PID + thread ID.
