### ISSUE TITLE
Implement pipe/pipe2

### ISSUE THREAD

**Issue by tiif** [rust-lang/miri#3746]
As mentioned in https://github.com/rust-lang/miri/issues/3442#issuecomment-2097703842, it is fairly easy to implement ``pipe/pipe2`` after https://github.com/rust-lang/miri/pull/3609. The main difference between ``socketpair`` and ``pipe`` is ``socketpair`` is bidirectional where ``pipe`` is unidirectional, other logics should be similar. The usage is also quite high according to [the shim wishlist](https://github.com/rust-lang/miri/issues/2057).

**Comment by RalfJung** [comment]
> The usage is also quite high according to https://github.com/rust-lang/miri/issues/2057.

I suspect most of that is due to uses of `Command`, which involves constructing a pipe... so adding support for `pipe2` will just lead to a slightly nicer error, saying that `fork` is not supported. But that's still a nice improvement, `fork` is the actual culprit here and I don't think we'll ever support it.
