### ISSUE TITLE
Symbolic execution support

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/miri#440]
Adding symbolic execution support (meaning some memory spaces don't have bytes, they just have a symbol which can contain arbitrary data depending on the problem being solved (e.g. they can contain the tree `arg0 + arg1` if these args are unknown))

This is useful for:

* testing functions for memory bugs without having known input arguments
* implementing const generic unification (so knowing that `C + C + 1` is the same as `2 * C + 2 - 1` without knowing `C`)
* evaluating associated constants of traits with generic parameters

**Comment by bjorn3** [comment]
I recall having seen a fork of miri doing this some time ago, but I can't recall its name.

**Comment by bjorn3** [comment]
@Bobo1239 thanks, that's it. :+1:

**Comment by RalfJung** [comment]
Woah... how do you think that will be possible without making everything painfully abstract or painfully slow?^^

I mean, I agree with the goal, I just think it is impossible. Not that this has ever stopped anyone in Rust land ;)

**Comment by oli-obk** [comment]
We already have the `Machine` abstraction. It would of course now have to infect `Allocation` and `Scalar` and bubble up from there. I just opened the issue to not forget about the use cases.

**Comment by RalfJung** [comment]
Okay. Currently, `Allocation` I think goes through some lengths to NOT depend on the `Machine`.

Also, a *lot* of code assumes it can turn a scalar into an integer and work with that.

**Comment by perlindgren** [comment]
Yes, by symbolic execution you may prove/reject  "const generic unification (so knowing that C + C + 1 is the same as 2 * C + 2 - 1 without knowing C."  (Problems may arise due to panicing behavior, which may pose a "cut", which leads to partial correctness/equivalence, etc. so the question is what we mean by "same as". 

The problem with Seer (and symbolic execution in general) is that it involves an (SMT) solver for the path constraints (under partially symbolic assignments). This may lead to vast number of queries, each one complex to solve, thus may be computationally expensive. However, if applied only to cases  of const generics, it would not affect the overall compiler performance (besides const generics I mean), so it could be price we are willing to pay. 

For finding memory bugs (array indexing etc.), it could be done either for a specific application or on library functions. In the former case, the application implies assumptions on the path conditions, and can therefore prove the absence of memory bugs for specific use cases, see e.g., No Panic! https://ieeexplore.ieee.org/abstract/document/8471992, where we apply KLEE for symbolic execution of rust code at LLVM-IR level. 

To the latter case (library code), one can prove absence of memory bugs as well, but that would likely require contracts, stating the assumptions. A primitive way is to use "klee-assume", but that does not give us quantification, thus we cannot generalize (klee assumptions are on the form of expressions.) With Seer and integration to the Rust compiler/language we may do better (adding path constraints on the form of first order logic, which would allow for quantification). 

In any case bringing in symbolic execution would add extra dependencies to the rust compiler (e.g., Z3 in the case of Seer). 

Regarding const function evaluation, I assume there is still a lot of untapped potential with MIRI, I'm not sure the status on that (what is in the pipeline for the compiler team).

**Comment by perlindgren** [comment]
On another note regarding symbolic execution, where it really hurts is when introducing lots of data dependencies causing path explosion, e.g. bubble sort. But if we are interested only in finding memory bugs, not the actual results of execution, each path needs to be visited just once (under the least restrictive constraint possible), so perhaps that is doable. KLEE at least has some notion of "visit once". If the purpose is just bug finding, one could think of symbolic execution as a superpowered lint pass in the compiler (an opt in pass as a complement to ordinary regression testing).

**Comment by christianpoveda** [comment]
> Problems may arise due to panicing behavior, which may pose a "cut", which leads to partial correctness/equivalence, etc. so the question is what we mean by "same as".

It wouldn't be enough to assume that two functions are equal if they panic for the same inputs?

**Comment by perlindgren** [comment]
Yes, intuitively, but I'm not sure if there might be something lurking. But I think its worth further exploring. Another thing that came to mind. There are some limitations to the Seer implementation, if I recall correctly it does not cover all legal Rust programs.

**Comment by oli-obk** [comment]
I think Kani and other MIR based projects have this well covered and we don't need to try to add it to miri.
