### ISSUE TITLE
Test whether self-referential futures are compatible with stacked borrows

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#532]
I have no idea if an `async` function that borrows across a yield point is compatible with Stacked Borrows. We should find out! I just am not sure how.

@cramertj @withoutboats I could use your help. :)  What is a minimal example for code that creates a self-referential future and then runs it? Ideally with no dependencies beyond libstd but that might not be possible.^^ Also, if there are different cases/"kinds" of self-referential fields in futures, we should make sure we cover all of them.

rustc must test these things somehow, right? Might be worth looking into that, too.

**Comment by Nemo157** [comment]
I'm actually working on trying to create a step-by-step example of how an `async fn` is first transformed into a self-referential generator then into a state machine. I should have a nice small self-contained example that uses both references into upvars and local variables ready in the next couple of days. (I already have [this playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d98b9b624501c2cc6fb6257552d1cdbd) that I intended to use, but I just realised I made a mistake in expanding `await!` that means this doesn't actually require self-references into local variables, just upvars).

> if there are different cases/"kinds" of self-referential fields in futures, we should make sure we cover all of them

There are only two different kinds that I know of, and fundamentally they should be the same. You can have references to upvars that have been moved into the generator and references to locals created while the generator is running. Once the generator transform has run these both just become references into the generator state variable, and I don't think they're distinguishable in the MIR.

**Comment by Nemo157** [comment]
Actually I might as well throw something together now, [here](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b7bca9b3118e6e167cbc729c28123e5d) should be a small example showing all kinds of references in an `async fn`. `y` is an upvar of the generator created in `foo` and `z` is a local of it; a reference to each are moved into the `async` block on line 14, inside `await!` the result of this block is stored into a local variable (so that variable is referencing both `y` and `z` in the outer generator) and polled to completion over a yield point. `a` is a local of the generator which has a reference taken but is dereferenced and dropped without hitting a yield point. Finally `x` is kept as reference out of the generator environment, as an example of non-self-referential references.

There's also the minimal framework for running an `async fn` inside `main`, this may be changing a little bit in the near future in a couple of ways, but I'll be creating an up-to-date version of this example as it does.

**Comment by RalfJung** [comment]
@cramertj Thanks! I thought there had to be `async` and a `Future`. I clearly know nothing about how async functions work.^^

**Comment by RalfJung** [comment]
To my big surprise, [this actually passes in miri](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=da4c25c087f95fee24bca495f2269cb3) :D

**Comment by RalfJung** [comment]
@withoutboats That makes sense, I wasn't aware of the layering here. This seems covered by https://github.com/solson/miri/pull/536 though, and it's actually working (with a small rustc fix), which is great!

However, something like @Nemo157's example also seems like a nice addition. Thanks for that @Nemo157! It also seems to pass, to my ever greater surprise.^^

**Comment by withoutboats** [comment]
This bug would have also been eliminated when the desugaring uses some sort of resume argument instead of TLS (that is, the entire context in which the mistake occurred is incidental complexity to the implementation)

**Comment by RalfJung** [comment]
Turns out I was very right to be suspicious, but didn't come up with the right test case. But the issue with Stacked Borrows and self-referential generators is a spec one, not a Miri one, so it is being tracked at https://github.com/rust-lang/unsafe-code-guidelines/issues/148.
