### ISSUE TITLE
Miri should support unwinding after a panic

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#658]
Currently, Miri only supports panic=abort, basically -- execution gets stopped on a panic.

We should support proper unwinding.

**Comment by matklad** [comment]
Run into an interesting case of this in https://github.com/matklad/once_cell/pull/63. 

I use `assert!(caller-enforced-invariant)` before unsafe code to guard against UB. So, I am specifically interested to run the test under miri, because "there's no UB" is exactly what the test is supposed to check.
