### ISSUE TITLE
SIMD instructions are not supported

### ISSUE THREAD

**Issue by ghost** [rust-lang/miri#662]
```
constant evaluation error: tried to call a function with ABI RustIntrinsic using caller ABI PlatformIntrinsic
   --> …/nightly-2019-03-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/../stdsimd/crates/core_arch/src/x86/sse2.rs:819:27
    |
819 |     transmute::<i8x16, _>(simd_eq(a.as_i8x16(), b.as_i8x16()))
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ tried to call a function with ABI RustIntrinsic using caller ABI PlatformIntrinsic
    |
    = note: inside call to `std::arch::x86_64::_mm_cmpeq_epi8` at …/memchr/src/x86/sse2.rs:189:34
    = note: inside call to `memchr::x86::sse2::forward_search1` at …/memchr/src/x86/sse2.rs:118:22
    = note: inside call to `memchr::x86::sse2::memchr`
```

**Comment by RalfJung** [comment]
Miri currently does not support SIMD instructions at all. Let's use this issue to track that (I don't think we have one already).

**Comment by RalfJung** [comment]
@flagello a piece of example code would help. Calling `memchr` should not usually invoke SIMD on Miri, I don't think?

**Comment by flagello** [comment]
If the machine supports them why not? Consider it‘s `rust-memchr` rather than `libc`‘s, and it prefers its own SIMD variants where possible.

**Comment by oli-obk** [comment]
Related: https://github.com/rust-rfcs/const-eval/issues/7

**Comment by RalfJung** [comment]
> the machine

Miri interprets your program, it doesn't run it directly on the hardware. The capabilities of the host machine do not matter.

> why not?

Because nobody went through the effort of implementing several hundred SIMD intrinsics yet.

**Comment by flagello** [comment]
> > the machine
> 
> Miri interprets your program, it doesn't run it directly on the hardware. The capabilities of the host machine do not matter.
> 
> > why not?
> 
> Because nobody went through the effort of implementing several hundred SIMD intrinsics yet. It's not that we don't want SIMD support, we do, but it's a lot of work.

Sorry, I wasn‘t clear enough—with “why not” I meant “why shouldn‘t `memchr` invoke SIMD on Miri when, e.g., `target_arch` is `x86_64`.” In fact, thank you for your work on Miri!

**Comment by RalfJung** [comment]
> with “why not” I meant “why shouldn‘t memchr invoke SIMD on Miri when, e.g., target_arch is x86_64.” 

Ah. That's a good question indeed. :)

Code doing opportunistic SIMD usually relies on [`align_to`](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.align_to). When running in Miri, this method always returns an empty middle slice. That's why the `memchr` in libstd works fine in Miri.

**Comment by flagello** [comment]
`libcore`‘s `memchr` (i.e., [`core::slice::memchr::memchr`](https://github.com/rust-lang/rust/blob/master/src/libcore/slice/memchr.rs) behind `#![feature(slice_internals)]`, for anyone else reading) does not rely on explicit SIMD at all as it‘s Andrew‘s “fallback” ([`memchr::memchr::fallback`](https://github.com/BurntSushi/rust-memchr/blob/master/src/fallback.rs)) implementation rather than the [SSE + AVX ones](https://github.com/BurntSushi/rust-memchr/tree/master/src/x86) (which are those that lead to the error when the requirements are satisfied).

**Comment by RalfJung** [comment]
A little update on this: the issue of supporting SIMD in MIR-based Rust verification tools came up at the Rust Verification Workshop at ETAPS, and there is a lot of interest in finding a shared solution. One avenue we are considering is to have a pure Rust implementation of those intrinsics; tools consuming MIR or LLVM IR should be able to compile that implementation to the required IR and replace intrinsic calls with that IR.

**Comment by RalfJung** [comment]
Miri now supports the intrinsics needed for potable_simd, which I think closes this issue.
